### PR TITLE
Use drag direction to determine autoscroll trigger

### LINKED ISSUE #33: Autoscroll being trigger triggered unecesarily on initial drag
### Description

Sometimes, when reordering a list, dragging an element is still scrolls the list. This only seems to occur when dragging very close to the top of the list. See attached video. 

https://github.com/user-attachments/assets/d44f0666-0176-44d1-a280-658a1a5a5d4e

### Steps to reproduce

1. Scroll to an initial position ~half the first element
2. Drag the first element down
3. Notice that the list scrolls up, as if a pan gesture without reordering occurred. 

### Minimal reproducible example

TODO

### Relevant logs

_No response_

### Reorderable List version

0.11.0

### React Native version

0.76.6

### Project type

Expo

### Architecture

Paper (Old Architecture)

### Reanimated version

3.16.2

### Gesture Handler version

2.22.0

### Affected platforms

iOS

### PR DESCRIPTION
**Pull request by JacobJaffe**
Closes #33 

The bug:
When dragging an item that *starts* in an autoscroll region, the autoscroll is immediately triggered, even if the intended scroll direction would have been against the scroll. 

The solution:
Use `currentTranslationY`, which is synced with the Pan gesture drag delta, to determine if the trigger was caused by moving into the drag region.

After:
https://github.com/user-attachments/assets/8e6b7122-f730-476b-86ff-5460da914878

### CODE REVIEW

**Comment by JacobJaffe** [comment]
@omahili Took a stab at fixing this issue. This is a pretty simple way of addressing it, using drag direction to block entering the autoscroll state if it doesn't match the autoscroll region (dragging down / up for top / bottom).

I tested this on an iOS simulator against the examples, and it seems to be working. I haven't tested this on a physical build or on android though. Hoping this can kick things in the right direction. 

I did encounter some weirdness with items jumping around while autoscrolling, but I believe that's because of the issue in #34 , and this doesn't introduce new cases of that.

Let me know your thoughts, happy to help out how I can with these improvements.

File: src/components/ReorderableListCore/useReorderableListCore.ts [hunk 1]
```diff
@@ -582,9 +582,14 @@ export const useReorderableListCore = <T>({
       ) {
         setCurrentIndex(y);
 
-        if (scrollDirection(y) !== 0) {
-          if (state.value !== ReorderableListState.AUTOSCROLL) {
-            // trigger autoscroll
+        const _dragDirection = currentTranslationY.value > 0 ? 1 : -1;
+        const _scrollDirection = scrollDirection(y);
```
Comment (omahili) [inline src/components/ReorderableListCore/useReorderableListCore.ts:586]: Do you mind dropping underscore from the variable names? You can use `scrollDirection(y)` directly to avoid name conflicts.

File: src/components/ReorderableListCore/useReorderableListCore.ts [hunk 2]
```diff
@@ -582,9 +582,14 @@ export const useReorderableListCore = <T>({
...
+
+        if (state.value !== ReorderableListState.AUTOSCROLL) {
+          // Trigger scrolls when:
+          // 1. Within the threshold area (top or bottom of list)
+          // 2. Have dragged in the same direction as the scroll
+          if (_scrollDirection === _dragDirection) {
```
Comment (omahili) [inline src/components/ReorderableListCore/useReorderableListCore.ts:592]: I know it was like that before, but we probably can merge the two conditions together into `if (state.value === ReorderableListState.DRAGGED && currentDragDirection === scrollDirection(y))`

**Comment by omahili** [comment]
Hi @JacobJaffe, thanks for the contribution! Left a couple of comments, but I think we're on track for this fix.

File: src/components/ReorderableListCore/useReorderableListCore.ts (hunk 2 above)
Comment (JacobJaffe) [reply src/components/ReorderableListCore/useReorderableListCore.ts:592]: I think that'll cause a different functionality, because currently there's three cases:
1. enter `AUTOSCROLL` state
2. enter `DRAGGED` state
3. no-op

And the nested conditions allow (3) to occur. If those conditions are merged together, (2) would always be occurring, when it's currently no-op'ing

I originally had them merged and saw some weird behaviors when transitioning from other states (`IDLE`, `RELEASED`)

Comment (JacobJaffe) [reply src/components/ReorderableListCore/useReorderableListCore.ts:592]: Ah, I misread your comment actually. I thought you had said:
 `if (state.value  !== ReorderableListState.AUTOSCROLL && currentDragDirection === scrollDirection(y)`
(a combination of the _existing_ cases)

That makes more sense, I'll implement and test that.

Comment (JacobJaffe) [reply src/components/ReorderableListCore/useReorderableListCore.ts:592]: & I'm now seeing this is all within the gated condition for DRAGGED / AUTOSCROLL. Not sure why I saw a bug the first time, probably unrelated.

**Comment by JacobJaffe** [comment]
@omahili Updated with those changes!

**Comment by omahili** [comment]
Thanks Jacob! Something is broken with the CI, I'll look into it tomorrow so we can merge it and release it.

File: src/components/ReorderableListCore/useReorderableListCore.ts (hunk 2 above)
Comment (omahili) [reply src/components/ReorderableListCore/useReorderableListCore.ts]: Yep, I took some time to test it and it does lead to the issue you mentioned. The current code does account for it, I just forgot about that sorry! So we need a no-op how you said and the order of the checks matters, first gating the autoscroll area and direction check and then the state, so that if it's auto-scrolling we don't mess with the state. I added a comment and I changed it in the branch locally, should I push it if you don't mind?

One more issue I see now is that using `currentTranslationY` will narrow the autoscroll area if you drag an item within it. This happens because that stores the translation accumulated along y since the beginning of the pan gesture.

Comment (JacobJaffe) [reply src/components/ReorderableListCore/useReorderableListCore.ts]: >  I added a comment and I changed it in the branch locally, should I push it if you don't mind?

Yeah, go ahead on that, thanks

Comment (omahili) [reply src/components/ReorderableListCore/useReorderableListCore.ts]: > To make sure I understand:
> Given: an auto-scroll threshold of 50 px (y:[0, 50]), and an initial drag near the top (y:25)
> If the element is dragged down a lot, and then back up to the top, it needs to exceed y:25 (rather than the correct y:50) because it's using translationY?

Yes, exactly.

—

Maybe the first two points can be handled with a single shared value, with something like `lastDirectionTranslationY`. It's set to translationY on pan begin event, and then updated to translationY only when the direction changes on pan update event. 

Let's assume you store direction in a shared value `dragDirection` (point 4), it changes to `-1` (up) if e.translationY is smaller than the lastDirectionTranslationY minus the delta or it changes to `1` (down)  if e.translationY is bigger than the lastDirectionTranslationY plus the delta. `0` (none) is the initial value and dragDirection would need to be reset to it when the drag ends (placing that into the `resetSharedValues` function should be enough).

For now we could try with a hardcoded delta of 3? It can be converted into a prop later. How does this all sound to you?

Comment (omahili) [reply src/components/ReorderableListCore/useReorderableListCore.ts]: Pushed the no-op flow fix with a couple of comments.

Comment (JacobJaffe) [reply src/components/ReorderableListCore/useReorderableListCore.ts]: I think there's an edge case here whenever `dragDirection=0` (Here, that's just the base case at the start of the drag). 

For delta=11, the drag of `y:0 -> y:10 -> y:5 -> y-15` would keep the dragDirection locked at 0, since `lastDirectionTranslationY` would be set on each time a direction switch is determined (0, 9, 6). So for a "jittery" gesture panning in a direction, the direction could be "locked" at 0. 

I don't know how much that would matter when the delta is small enough, but I think that this could feasibly happen with physical gesture tracking to a degree that the perceived delta isn't consistent (Meaning sometimes it feels like it take "more" to trigger the start)

Comment (omahili) [reply src/components/ReorderableListCore/useReorderableListCore.ts]: Yes that is true, the delta needs to be small enough so that it doesn't cause this and big enough to be forgiving when changes are too small. A value of 2 can also be tested to see what's best.

One thing I want to correct is that `lastDirectionTranslationY` needs to be set only once the drag starts and not on any pan begin. Not doing so would lead to it being set randomly without a dragged item. That can be done by having its initial state to -1 that needs to be checked along with the dragged state, probably in both pan being and pan update.

Not sure I fully understand the solution you mention for the jitter at end, but if you think that would make it better you can try it. Also let me know if you'd like me to take over or you want to go ahead with this.

Comment (JacobJaffe) [reply src/components/ReorderableListCore/useReorderableListCore.ts]: Ah, I've been a little confused talking about `translationY`, in my head I've been thinking about this as a pivot point determined by the absolute position. 

I'm pushing an update to this now based on this. From testing I think a larger delta is needed to account for gesture noise. I've used 10 here, and it seems to account for the common case of holding an element in the autoscroll zone. 

Here's a clip of the new behavior. 

The red box shows the autoscroll region (10% default)
Notice how now an item dragged form the top of the box will trigger the auto-scroll upon entering the box again, rather than crossing the initial drag point (as was the previous behavior's issue). 

 

https://github.com/user-attachments/assets/ccbab0ac-7ff7-45bb-9d86-959e5eec57ee

Comment (JacobJaffe) [reply src/components/ReorderableListCore/useReorderableListCore.ts]: FWIW, I also tested using `velocityY` -- that's a simpler path for determining the current direction if not caring about a delta imo.

File: src/components/ReorderableListCore/useReorderableListCore.ts [hunk 3]
```diff
@@ -175,6 +177,23 @@ export const useReorderableListCore = <T>({
         })
         .onUpdate(e => {
           if (state.value !== ReorderableListState.RELEASED) {
+            // `dragDirection` determines if the user intends to autoscroll.
+            // We only update it if a threshold is passed to account for noise,
+            // especially while holding a dragged item within the scroll zone.
+            const direction = e.velocityY > 0 ? 1 : -1;
+            if (direction !== dragDirection.value) {
+              if (lastDragDirectionPivot.value === null) {
+                lastDragDirectionPivot.value = e.absoluteY;
```
Comment (JacobJaffe) [inline src/components/ReorderableListCore/useReorderableListCore.ts:186]: This case does *not* set the `dragDirection` because the delta has not been determined yet.

File: src/components/ReorderableListCore/useReorderableListCore.ts [hunk 4]
```diff
@@ -175,6 +177,23 @@ export const useReorderableListCore = <T>({
         })
         .onUpdate(e => {
           if (state.value !== ReorderableListState.RELEASED) {
+            // `dragDirection` determines if the user intends to autoscroll.
```
Comment (JacobJaffe) [inline src/components/ReorderableListCore/useReorderableListCore.ts:180]: Note that this only occurs in `onUpdate`. This could initialize the base case in the `onBegin` instead, but I found this more readable to keep it all in one place. That's just a 1 event difference (which requires a bunch of events anyways for the threshold delta), so I don't think there's any feeling difference.

File: src/components/ReorderableListCore/useReorderableListCore.ts [hunk 5]
```diff
@@ -124,6 +124,8 @@ export const useReorderableListCore = <T>({
   const duration = useSharedValue(animationDuration);
   const scaleDefault = useSharedValue(1);
   const opacityDefault = useSharedValue(1);
+  const dragDirection = useSharedValue(0);
+  const lastDragDirectionPivot = useSharedValue<null | number>(null);
```
Comment (JacobJaffe) [inline src/components/ReorderableListCore/useReorderableListCore.ts:128]: opted for `null` as the sentinel case because `-1` is a plausible value for a coordinate position.

File: src/components/ReorderableListCore/useReorderableListCore.ts (hunk 4 above)
Comment (omahili) [reply src/components/ReorderableListCore/useReorderableListCore.ts:180]: Ok, fair enough.

File: src/components/ReorderableListCore/useReorderableListCore.ts [hunk 6]
```diff
@@ -175,6 +177,23 @@ export const useReorderableListCore = <T>({
...
+                lastDragDirectionPivot.value = e.absoluteY;
+              } else {
+                if (
+                  Math.abs(e.absoluteY - lastDragDirectionPivot.value) >= 10
+                ) {
+                  dragDirection.value = direction;
+                  lastDragDirectionPivot.value = e.absoluteY;
+                }
+              }
+            }
```
Comment (omahili) [inline src/components/ReorderableListCore/useReorderableListCore.ts:195]: I think this needs to be wrapped into `if (state.value !== ReorderableListState.RELEASED)` or drag direction might be set on random pans leading to bugs. Maybe it can be moved to a function altogether, e.g. `setDragDirection`?

File: src/components/ReorderableListCore/useReorderableListCore.ts (hunk 2 above)
Comment (omahili) [reply src/components/ReorderableListCore/useReorderableListCore.ts]: Ah yeah, didn't think about velocity, good one. Looks good!

Comment (omahili) [reply src/components/ReorderableListCore/useReorderableListCore.ts]: Velocity would actually work even better.

File: src/components/ReorderableListCore/useReorderableListCore.ts [hunk 7]
```diff
@@ -187,14 +206,16 @@ export const useReorderableListCore = <T>({
...
-      scrollViewDragScrollTranslationY,
-      gestureState,
+      currentTranslationY,
       dragY,
-      startY,
-      state,
+      gestureState,
+      dragDirection,
+      dragScrollTranslationY.value,
+      scrollViewDragScrollTranslationY.value,
```
Comment (omahili) [inline src/components/ReorderableListCore/useReorderableListCore.ts:217]: We need to drop `.value` in the callback deps.

Comment (JacobJaffe) [reply src/components/ReorderableListCore/useReorderableListCore.ts:217]: Oops -- yes. Not sure why my linter added those.

File: src/components/ReorderableListCore/useReorderableListCore.ts (hunk 6 above)
[the remark this answers is not in the document]
Comment (JacobJaffe) [reply src/components/ReorderableListCore/useReorderableListCore.ts:195]: Should this be for:
```
state.value === ReorderableListState.DRAGGED ||
state.value === ReorderableListState.AUTOSCROLL
 ```
 
 To account for changing direction while in the autoscroll region?
 Currently, I've got this setup like that so that it allows cancelling autoscroll while within the region

File: src/components/ReorderableListCore/useReorderableListCore.ts [hunk 8]
```diff
@@ -174,6 +204,12 @@ export const useReorderableListCore = <T>({
           }
         })
         .onUpdate(e => {
+          if (
+            state.value === ReorderableListState.DRAGGED ||
+            state.value === ReorderableListState.AUTOSCROLL // <- comment this out to try only canceling when leaving the region
```
Comment (JacobJaffe) [inline src/components/ReorderableListCore/useReorderableListCore.ts:209]: @omahili this is the line in question -- commenting this out will change the behavior to cancel autoscroll when the direction doesn't match the threshold area, vs. when the gesture has left the threshold

Comment (omahili) [reply src/components/ReorderableListCore/useReorderableListCore.ts:209]: Both make sense indeed, but I'd also go without.

Something I've been thinking for a while is an autoscroll incremental speed based on the distance from the edge, which would allow you to slow down the autoscroll when you move in the opposite direction, instead of blocking it like this condition would do. But it's something I'm planning for v1.

Comment (JacobJaffe) [reply src/components/ReorderableListCore/useReorderableListCore.ts]: Sounds good -- this is now updated with just the first condition. 

I think having the speed slow down would be neat, especially if the scrolling was continuous.

Comment (omahili) [reply src/components/ReorderableListCore/useReorderableListCore.ts]: Hi @JacobJaffe, after testing I think 10 is a bit too high as a delta, I'll merge it and move it to a prop. Thanks for the PR!
